# This file can be used to override defaults for multirun arguments.
# These will be overridden by command-line arguments

maxNumberOfRuns: 20
executeWithGui: false
randomSeed: 123456789
startYear: 2011
endYear: 2050
popSize: 50000

# For arguments to pass to the SimPathsModel itself:
# Current model defaults can be overridden by uncommenting/changing
model_args:
  shockPropagation: true
  healthShock: false
  partnershipShock: false
  wageShock: false
  projectMortality: true
#    maxAge: 130
#    fixTimeTrend: true
#    timeTrendStopsIn: 2017
#    fixRandomSeed: true
#    sIndexTimeWindow: 5
#    sIndexAlpha: 2
#    sIndexDelta: 0
#    savingRate: 0
#    initialisePotentialEarningsFromDatabase: true
#    useWeights: false
#    useSBAMMatching:
#    projectMortality: true
#    alignFertility: true
#    labourMarketCovid19On: false
#    projectFormalChildcare: true
#    donorPoolAveraging: true
#    projectSocialCare: false
#    enableIntertemporalOptimisations: false
#    useSavedBehaviour: false
#    readGrid: "laptop serial"
#    saveBehaviour: true
#    employmentOptionsOfPrincipalWorker: 3
#    employmentOptionsOfSecondaryWorker: 3
#    responsesToEducation: true
#    responsesToRetirement: false
#    responsesToHealth: true
#    responsesToDisability: false
#    minAgeForPoorHealth: 50
#    responsesToRegion: false


collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0